name: Tests and Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write
  packages: write

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        
      - name: Run tests
        run: npm test
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.os }}
          path: |
            playwright-report/
            test-results/
          retention-days: 30 
          
      # 添加构建步骤 (仅在测试成功且为推送事件时运行)
      - name: Build application
        if: success() && github.event_name == 'push'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            npm run build:mac
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            npm run build:win
          fi
        shell: bash
      
      # 上传构建后的应用
      - name: Upload built application
        if: success() && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: chat-explorer-${{ matrix.os }}
          path: dist/
          retention-days: 7
  
  # 添加单独的发布任务，仅在所有测试和构建完成后运行
  release:
    needs: test
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      # 读取 package.json 中的版本号
      - name: Get version
        id: package_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        shell: bash
      
      # 删除已存在的相同版本Release(如果存在)
      - name: Delete existing release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: v${{ steps.package_version.outputs.version }}
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
          
      # 下载所有构建的应用程序
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      # 创建发布目录并只复制主要安装包文件，避免重复文件
      - name: Prepare release files
        run: |
          mkdir -p release-files
          # 为不同平台的构建文件创建不同的文件名前缀
          find artifacts/chat-explorer-macos-latest -name "*.dmg" -o -name "*.zip" | xargs -I{} cp {} release-files/mac-{}
          find artifacts/chat-explorer-macos-latest -name "*.dmg" -o -name "*.zip" | xargs -I{} basename {} | xargs -I{} mv release-files/mac-{} release-files/mac-{}
          
          find artifacts/chat-explorer-windows-latest -name "*.exe" | xargs -I{} cp {} release-files/win-{}
          find artifacts/chat-explorer-windows-latest -name "*.exe" | xargs -I{} basename {} | xargs -I{} mv release-files/win-{} release-files/win-{}
          
          # 检查和打印要发布的文件列表
          echo "Files to be published:"
          ls -la release-files/
        
      # 自动发布到 GitHub Releases，只发布主要安装包文件
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.package_version.outputs.version }}
          tag_name: v${{ steps.package_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            release-files/* 